// Codegen: src/tokens.ts (SSOT) → src/tokens.css (generated artifact).
//
//   node scripts/gen-tokens.ts      (Node ≥23.6 strips TS types natively — no deps)
//
// tokens.ts holds the *values* (typed, JS-importable); this script mirrors them
// into CSS custom properties so styles.css can `var(--funky-…)` them at runtime.
// Never hand-edit tokens.css — edit tokens.ts and re-run.

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import {
  color,
  role,
  shadow,
  radius,
  border,
  space,
  font,
  controlHeight,
  motion,
} from "../src/tokens.ts";

const PREFIX = "--funky-";

const decls: string[] = [];
const v = (name: string, value: string | number) =>
  decls.push(`  ${PREFIX}${name}: ${value};`);
const blank = () => decls.push("");
const note = (text: string) => decls.push(`  /* ${text} */`);

note("Color: surface");
v("bg", color.bg);
v("surface", color.surface);
v("sunken", color.sunken);
note("Color: ink");
v("ink", color.ink);
v("ink-muted", color.inkMuted);
v("ink-inverse", color.inkInverse);
note("Color: line");
v("line", color.line);
note("Color: accents (neon)");
v("pink", color.pink);
v("purple", color.purple);
v("cyan", color.cyan);
v("yellow", color.yellow);
v("orange", color.orange);
v("sky", color.sky);
v("green", color.green);
v("accent-soft", color.accentSoft);
note("Role aliases");
v("primary", role.primary);
v("secondary", role.secondary);
v("success", role.success);
v("warning", role.warning);
v("danger", role.danger);
v("info", role.info);
blank();

note("Shadow: hard offset solid (blur 0)");
v("shadow-sm", shadow.sm);
v("shadow-md", shadow.md);
v("shadow-lg", shadow.lg);
blank();

note("Shape");
v("radius", radius.none);
v("border-width", border.width);
v("border-width-bold", border.widthBold);
v("border-color", border.color);
v("border", `${border.width} solid ${border.color}`);
v("border-bold", `${border.widthBold} solid ${border.color}`);
blank();

note("Space");
v("space-xs", space.xs);
v("space-sm", space.sm);
v("space-md", space.md);
v("space-lg", space.lg);
v("space-xl", space.xl);
v("space-2xl", space["2xl"]);
blank();

note("Type");
v("font-family", font.family);
v("weight-medium", font.weight.medium);
v("weight-bold", font.weight.bold);
v("weight-black", font.weight.black);
v("size-2xs", font.size["2xs"]);
v("size-xs", font.size.xs);
v("size-sm", font.size.sm);
v("size-md", font.size.md);
v("size-lg", font.size.lg);
v("size-xl", font.size.xl);
v("size-2xl", font.size["2xl"]);
v("size-3xl", font.size["3xl"]);
v("size-4xl", font.size["4xl"]);
v("chrome-transform", font.chrome.transform);
v("chrome-tracking", font.chrome.tracking);
blank();

note("Control heights");
v("control-sm", controlHeight.sm);
v("control-md", controlHeight.md);
v("control-lg", controlHeight.lg);
blank();

note("Motion: press-into-shadow");
v("motion-duration", motion.duration);
v("motion-easing", motion.easing);
v("press-offset", motion.pressOffset);

const css = `/* AUTO-GENERATED by scripts/gen-tokens.ts — do not edit.
   Source of truth is src/tokens.ts. Re-run: node scripts/gen-tokens.ts */

@import url("https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css");

:root {
${decls.join("\n")}
}

/* ── Base reset ── */
*,
*::before,
*::after {
  box-sizing: border-box;
}

body {
  margin: 0;
  background: var(${PREFIX}bg);
  color: var(${PREFIX}ink);
  font-family: var(${PREFIX}font-family);
  font-size: var(${PREFIX}size-md);
  -webkit-font-smoothing: antialiased;
}

/* ── Helper utility classes (optional reuse) ── */
.funky-shadow-sm { box-shadow: var(${PREFIX}shadow-sm); }
.funky-shadow-md { box-shadow: var(${PREFIX}shadow-md); }
.funky-shadow-lg { box-shadow: var(${PREFIX}shadow-lg); }
.funky-border { border: var(${PREFIX}border); }
.funky-chrome {
  text-transform: var(${PREFIX}chrome-transform);
  font-weight: var(${PREFIX}weight-black);
  letter-spacing: var(${PREFIX}chrome-tracking);
}
`;

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, "../src/tokens.css");
writeFileSync(out, css);
console.log(`✓ wrote ${out} (${decls.filter((l) => l.includes(":")).length} tokens)`);
